(function() {var implementors = {};
implementors["layout_thread"] = ["impl&lt;'le&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/layout_wrapper/struct.ServoLayoutElement.html' title='script::layout_wrapper::ServoLayoutElement'>ServoLayoutElement</a>&lt;'le&gt;","impl&lt;'le&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/layout_wrapper/struct.ServoThreadSafeLayoutElement.html' title='script::layout_wrapper::ServoThreadSafeLayoutElement'>ServoThreadSafeLayoutElement</a>&lt;'le&gt;",];
implementors["script"] = ["impl&lt;'a&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/dom/bindings/js/struct.Root.html' title='script::dom::bindings::js::Root'>Root</a>&lt;<a class='struct' href='script/dom/element/struct.Element.html' title='script::dom::element::Element'>Element</a>&gt;","impl&lt;'le&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/layout_wrapper/struct.ServoLayoutElement.html' title='script::layout_wrapper::ServoLayoutElement'>ServoLayoutElement</a>&lt;'le&gt;","impl&lt;'le&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/layout_wrapper/struct.ServoThreadSafeLayoutElement.html' title='script::layout_wrapper::ServoThreadSafeLayoutElement'>ServoThreadSafeLayoutElement</a>&lt;'le&gt;",];
implementors["servo"] = ["impl&lt;'le&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/layout_wrapper/struct.ServoLayoutElement.html' title='script::layout_wrapper::ServoLayoutElement'>ServoLayoutElement</a>&lt;'le&gt;","impl&lt;'le&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='script/layout_wrapper/struct.ServoThreadSafeLayoutElement.html' title='script::layout_wrapper::ServoThreadSafeLayoutElement'>ServoThreadSafeLayoutElement</a>&lt;'le&gt;",];
implementors["style"] = ["impl&lt;'a, E&gt; <a class='trait' href='selectors/tree/trait.Element.html' title='selectors::tree::Element'>Element</a> for <a class='struct' href='style/restyle_hints/struct.ElementWrapper.html' title='style::restyle_hints::ElementWrapper'>ElementWrapper</a>&lt;'a, E&gt; <span class='where'>where E: <a class='trait' href='style/dom/trait.TElement.html' title='style::dom::TElement'>TElement</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
