(function() {var implementors = {};
implementors["arrayvec"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["brotli"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["core"] = [];
implementors["cssparser"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["enum_primitive"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["gfx"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["gleam"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["glutin"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["glx"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["heartbeats_simple"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["html5ever"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["hyper"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["image"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["ipc_channel"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["layout_thread"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["lazy_static"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["libc"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["libloading"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["mime_guess"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["mio"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["net_traits"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["offscreen_gl_context"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["openssl"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["phf"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["regex_syntax"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["script"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["servo"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["servo_config"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["servo_rand"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["servo_remutex"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["servo_url"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["shared_library"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["std_unicode"] = [];
implementors["string_cache"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["style"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["syn"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["tendril"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["url"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["void"] = [];
implementors["webrender"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["websocket"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["webvr_traits"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["ws"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];
implementors["xml5ever"] = ["impl&lt;'a, 'b&gt; <a class="trait" href="core/str/pattern/trait.Pattern.html" title="trait core::str::pattern::Pattern">Pattern</a>&lt;'a&gt; for &amp;'b <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
