(function() {var implementors = {};
implementors["serde"] = ["impl <a class="trait" href="serde/core/ops/trait.Add.html" title="trait serde::core::ops::Add">Add</a>&lt;<a class="struct" href="std/time/duration/struct.Duration.html" title="struct std::time::duration::Duration">Duration</a>&gt; for <a class="struct" href="std/time/duration/struct.Duration.html" title="struct std::time::duration::Duration">Duration</a>","impl <a class="trait" href="serde/core/ops/trait.Add.html" title="trait serde::core::ops::Add">Add</a>&lt;<a class="struct" href="std/time/duration/struct.Duration.html" title="struct std::time::duration::Duration">Duration</a>&gt; for <a class="struct" href="std/time/struct.Instant.html" title="struct std::time::Instant">Instant</a>","impl <a class="trait" href="serde/core/ops/trait.Add.html" title="trait serde::core::ops::Add">Add</a>&lt;<a class="struct" href="std/time/duration/struct.Duration.html" title="struct std::time::duration::Duration">Duration</a>&gt; for <a class="struct" href="std/time/struct.SystemTime.html" title="struct std::time::SystemTime">SystemTime</a>","impl&lt;'a&gt; <a class="trait" href="serde/core/ops/trait.Add.html" title="trait serde::core::ops::Add">Add</a>&lt;&amp;'a <a class="primitive" href="std/primitive.str.html">str</a>&gt; for <a class="enum" href="collections/borrow/enum.Cow.html" title="enum collections::borrow::Cow">Cow</a>&lt;'a, <a class="primitive" href="std/primitive.str.html">str</a>&gt;","impl&lt;'a&gt; <a class="trait" href="serde/core/ops/trait.Add.html" title="trait serde::core::ops::Add">Add</a>&lt;<a class="enum" href="collections/borrow/enum.Cow.html" title="enum collections::borrow::Cow">Cow</a>&lt;'a, <a class="primitive" href="std/primitive.str.html">str</a>&gt;&gt; for <a class="enum" href="collections/borrow/enum.Cow.html" title="enum collections::borrow::Cow">Cow</a>&lt;'a, <a class="primitive" href="std/primitive.str.html">str</a>&gt;","impl&lt;'a&gt; <a class="trait" href="serde/core/ops/trait.Add.html" title="trait serde::core::ops::Add">Add</a>&lt;&amp;'a <a class="primitive" href="std/primitive.str.html">str</a>&gt; for <a class="struct" href="collections/string/struct.String.html" title="struct collections::string::String">String</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
