(function() {var implementors = {};
implementors["serde"] = ["impl&lt;'a, 'b, T, S&gt; <a class="trait" href="serde/core/ops/trait.BitOr.html" title="trait serde::core::ops::BitOr">BitOr</a>&lt;&amp;'b <a class="struct" href="std/collections/hash/set/struct.HashSet.html" title="struct std::collections::hash::set::HashSet">HashSet</a>&lt;T, S&gt;&gt; for &amp;'a <a class="struct" href="std/collections/hash/set/struct.HashSet.html" title="struct std::collections::hash::set::HashSet">HashSet</a>&lt;T, S&gt; <span class="where fmt-newline">where S: <a class="trait" href="serde/core/hash/trait.BuildHasher.html" title="trait serde::core::hash::BuildHasher">BuildHasher</a> + <a class="trait" href="serde/export/trait.Default.html" title="trait serde::export::Default">Default</a>,<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;T: <a class="trait" href="serde/core/cmp/trait.Eq.html" title="trait serde::core::cmp::Eq">Eq</a> + <a class="trait" href="serde/core/hash/trait.Hash.html" title="trait serde::core::hash::Hash">Hash</a> + <a class="trait" href="core/clone/trait.Clone.html" title="trait core::clone::Clone">Clone</a></span>","impl&lt;'a, 'b, T&gt; <a class="trait" href="serde/core/ops/trait.BitOr.html" title="trait serde::core::ops::BitOr">BitOr</a>&lt;&amp;'b <a class="struct" href="collections/btree/set/struct.BTreeSet.html" title="struct collections::btree::set::BTreeSet">BTreeSet</a>&lt;T&gt;&gt; for &amp;'a <a class="struct" href="collections/btree/set/struct.BTreeSet.html" title="struct collections::btree::set::BTreeSet">BTreeSet</a>&lt;T&gt; <span class="where fmt-newline">where T: <a class="trait" href="serde/core/cmp/trait.Ord.html" title="trait serde::core::cmp::Ord">Ord</a> + <a class="trait" href="core/clone/trait.Clone.html" title="trait core::clone::Clone">Clone</a></span>","impl&lt;E&gt; <a class="trait" href="serde/core/ops/trait.BitOr.html" title="trait serde::core::ops::BitOr">BitOr</a>&lt;<a class="struct" href="collections/enum_set/struct.EnumSet.html" title="struct collections::enum_set::EnumSet">EnumSet</a>&lt;E&gt;&gt; for <a class="struct" href="collections/enum_set/struct.EnumSet.html" title="struct collections::enum_set::EnumSet">EnumSet</a>&lt;E&gt; <span class="where fmt-newline">where E: <a class="trait" href="collections/enum_set/trait.CLike.html" title="trait collections::enum_set::CLike">CLike</a></span>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
